import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "assets/pic.jpeg",
    title: "Lab test",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: `assets/pic1.jpeg`,
    title: "Lab tests",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },

  {
    img: `assets/pic2.jpeg`,
    title: "Lab tests",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },
  // {
  //   img: assets/pic3.jpg,
  //   title: "Lab tests",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "200",
  //   company: "Adidas",
  //   color: "black",
  //   category: "sneakers",
  // },
  {
    img: `assets/pic4.jpeg`,
    title: "Lab tests",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Vans",
    color: "green",
    category: "flats",
  },
  {
    img: `assets/pic4.jpeg`,
    title: "lab tests",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "flats",
  },

  {
    img: `assets/pic5.png`,
    title: "Lab tests",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Vans",
    color: "white",
    category: "flats",
  },

  {
    img: `assets/pic.jpeg`,
    title: "Lab tests",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Vans",
    color: "white",
    category: "flats",
  },
  {
    img: "assets/pic.jpeg",
    title: "Lab test",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "assets/pic.jpeg",
    title: "Lab test",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },

  {
    img: `assets/pic4.jpeg`,
    title: "Lab tests",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Vans",
    color: "green",
    category: "flats",
  },
  // {
  //   img: "https://m.media-amazon.com/images/I/71E75yRwCDL.AC_UY575.jpg",
  //   title: "Pacer Future Sneaker",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "150",
  //   company: "Puma",
  //   color: "red",
  //   category: "sneakers",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/71jeoX0rMBL.AC_UX575.jpg",
  //   title: "Unisex-Adult Super",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "150",
  //   company: "Puma",
  //   color: "black",
  //   category: "sneakers",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL.AC_UX575.jpg",
  //   title: "Roma Basic Sneaker",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "150",
  //   company: "Puma",
  //   color: "white",
  //   category: "sneakers",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/7128-af7joL.AC_UY575.jpg",
  //   title: "Pacer Future Doubleknit",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "150",
  //   company: "Puma",
  //   color: "black",
  //   category: "sneakers",
  // },

  // {
  //   img: "https://m.media-amazon.com/images/I/81xXDjojYKS.AC_UX575.jpg",
  //   title: "Fusion Evo Golf Shoe",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "100",
  //   company: "Puma",
  //   color: "green",
  //   category: "sneakers",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/719gdz8lsTS.AC_UX575.jpg",
  //   title: "Rainbow Chex Skate",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "100",
  //   company: "Vans",
  //   color: "red",
  //   category: "flats",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/71gpFHJlnoL.AC_UX575.jpg",
  //   title: "Low-Top Trainers",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "100",
  //   company: "Vans",
  //   color: "white",
  //   category: "sandals",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/71pf7VFs9CL.AC_UX575.jpg",
  //   title: "Vans Unisex Low-Top",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "100",
  //   company: "Vans",
  //   color: "blue",
  //   category: "sandals",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/61N4GyWcHPL.AC_UY575.jpg",
  //   title: "Classic Bandana Sneakers",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "50",
  //   company: "Nike",
  //   color: "black",
  //   category: "sandals",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/61bncQ44yML.AC_UX695.jpg",
  //   title: "Chunky High Heel",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "50",
  //   company: "Vans",
  //   color: "black",
  //   category: "heels",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/71czu7WgGuL.AC_UY695.jpg",
  //   title: "Slip On Stiletto High Heel",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "100",
  //   company: "puma",
  //   color: "black",
  //   category: "heels",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/61men05KRxL.AC_UY625.jpg",
  //   title: "DREAM PAIRS Court Shoes",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "150",
  //   company: "Nike",
  //   color: "red",
  //   category: "heels",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/519MRhRKGFL.AC_UX575.jpg",
  //   title: "Nike Air Vapormax Plus",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "200",
  //   company: "Nike",
  //   color: "red",
  //   category: "sneakers",
  // },

  // {
  //   img: "https://m.media-amazon.com/images/I/51PGWTXgf-L.AC_UY625.jpg",
  //   title: "Low Mid Block Heels",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "200",
  //   company: "Nike",
  //   color: "black",
  //   category: "heels",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/616sA5XUKtL.AC_UY675.jpg",
  //   title: "Chunky High Heel",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "50",
  //   company: "Adidas",
  //   color: "black",
  //   category: "heels",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/71h5+MbEK7L.AC_UY625.jpg",
  //   title: "Amore Fashion Stilettos",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "150",
  //   company: "Adidas",
  //   color: "white",
  //   category: "heels",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/61uw5RDxKQL.AC_UY625.jpg",
  //   title: "Bridal Sandals Glitter",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "50",
  //   company: "Adidas",
  //   color: "black",
  //   category: "heels",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/71yhoZP0l6L.AC_UY695.jpg",
  //   title: "Wedding Prom Bridal",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "50",
  //   company: "Adidas",
  //   color: "black",
  //   category: "flats",
  // },
];

export default data;
